name: Daily Swertres Scraper

on:
  schedule:
    # Runs at 3:05 AM, 8:05 AM, 1:05 PM UTC (equivalent to 11:05 AM, 4:05 PM, 9:05 PM PHT)
    - cron: '5 3,8,13 * * *'
  workflow_dispatch: # Allows manual run inside GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-with: '3.10'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4

    - name: Run Scraper
      run: python scraper.py

    - name: Commit and Push Results
      run: |
        git config --global user.name "Github Action Bot"
        git config --global user.email "actions@github.com"
        git add results.json
        git commit -m "Update Swertres results [skip ci]" || exit 0
        git push
